[package]
name = "srcds_log_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "srcds_log_parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
nom = "7.1"
regex = "1.10"
